# Generated by Django 5.2.8 on 2025-12-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('agent', 'Agent'), ('cashier', 'Cashier')], default='agent', max_length=20),
        ),
    ]
