# Generated by Django 5.2.8 on 2025-12-20 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('buyer_name', models.CharField(max_length=200)),
                ('buyer_phone', models.CharField(max_length=20)),
                ('buyer_email', models.CharField(blank=True, max_length=255, null=True)),
                ('buyer_id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('cart_data', models.TextField(help_text='JSON data of cart items')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('item_count', models.PositiveIntegerField()),
                ('payment_method', models.CharField(default='cash', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('sale_id', models.CharField(blank=True, max_length=50, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pending_orders',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='pending_ord_status_9fe076_idx'), models.Index(fields=['buyer_phone'], name='pending_ord_buyer_p_f05cb4_idx')],
            },
        ),
    ]
