# Generated by Django 5.2.8 on 2025-12-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_pendingorder_item_count_pendingorderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pendingorderitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='pendingorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Review'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterModelTable(
            name='pendingorderitem',
            table='pending_order_items',
        ),
    ]
