# Generated by Django 5.2.8 on 2025-12-02 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('item_type', models.CharField(choices=[('single', 'Single Item'), ('bulk', 'Bulk Item')], help_text='Single: Unique items (phones). Bulk: Stock items (cables)', max_length=10)),
                ('sku_type', models.CharField(choices=[('imei', 'IMEI NUMBER'), ('serial', 'SERIAL NUMBER'), ('barcode', 'BARCODE')], help_text='Type of identifier for this category', max_length=10)),
                ('category_code', models.CharField(blank=True, max_length=10, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name (e.g., Samsung S24)', max_length=255)),
                ('product_code', models.CharField(blank=True, db_index=True, max_length=20, unique=True)),
                ('sku_value', models.CharField(blank=True, db_index=True, help_text='IMEI, Serial Number, or Barcode', max_length=200, null=True)),
                ('quantity', models.PositiveIntegerField(default=1, help_text='1 for single items, multiple for bulk items')),
                ('buying_price', models.DecimalField(decimal_places=2, help_text='Cost price', max_digits=12)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Retail price', max_digits=12)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold', 'Sold'), ('lowstock', 'Low Stock'), ('outofstock', 'Out of Stock')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='inventory.category')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Positive for stock IN, Negative for stock OUT')),
                ('entry_type', models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('return', 'Return'), ('adjustment', 'Adjustment')], max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Price per unit at time of transaction', max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total transaction value', max_digits=12)),
                ('reference_id', models.CharField(blank=True, help_text='Invoice/Receipt/Order number', max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_entries', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='Product this entry affects', on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='inventory.product')),
            ],
            options={
                'verbose_name': 'Stock Entry',
                'verbose_name_plural': 'Stock Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'status'], name='inventory_p_categor_3c59e3_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku_value'], name='inventory_p_sku_val_72a9b1_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-created_at'], name='inventory_p_created_711f60_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['-created_at'], name='inventory_s_created_3e718e_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['entry_type'], name='inventory_s_entry_t_e83f6a_idx'),
        ),
        migrations.AddIndex(
            model_name='stockentry',
            index=models.Index(fields=['product', '-created_at'], name='inventory_s_product_452578_idx'),
        ),
    ]
