# Generated by Django 5.2.8 on 2025-12-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockentry',
            name='entry_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('sale', 'Sale'), ('reversal', 'Reversal'), ('adjustment', 'Adjustment')], max_length=20),
        ),
    ]
