# Generated by Django 5.2.8 on 2025-12-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Product image (optional)', null=True, upload_to='products/%Y/%m/'),
        ),
    ]
