# Generated by Django 5.2.8 on 2025-12-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleCounter',
            fields=[
                ('year', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True)),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Sale Counter',
                'verbose_name_plural': 'Sale Counters',
                'db_table': 'sale_counters',
            },
        ),
    ]
